### ISSUE TITLE
Inserting a list of common resolutions in config.ini for custom resolutions

### ISSUE THREAD

**Issue by Jeremiidesu** [Rayduxz/DIVA-Loader#6]
I'd suggest inserting as comment a list of common resolutions (maybe including absurd ones) in order to aid selection in config.ini, like so:

```toml
# Set internal render resolution (not windows size!)
# HD    : 1280x720
# FHD   : 1920x1080
# WQHD  : 2560x1440
# 4K UHD: 3840x2160
# 8K UHD: 7680x4320
r.Enable = 1
r.Width = 3840
r.Height = 2160
```
